### ISSUE TITLE
Multiple query definitions in a single file cause duplicate classes

### ISSUE THREAD

**Issue by Kenoshen** [comigor/artemis#169]
**Bug description**
I am probably doing something wrong or unexpected here, but basically I am trying to generate my dart query files by running `flutter pub run build_runner build`.  The command fails with the following error:

Output Error:
```
Exception: Two classes were generated with the same name `Users$Query`!
You may want to:
- Make queries_glob stricter, to gather less .graphql files on a single output
- Use alias on one of the places a field of type `Users$Query` is requested
- File a bug on artemis ...

```

I found that if I only have a single `query X {...}` in the `queries_glob:` file then the command succeeds and the .dart file is generated.  However, as soon as the `queries_glob:` file contains more than one `query X {...}` then I see the above error.  It seems to throw on the first query in the file.

A possible workaround then seems to be that I could create a single schema_mapping for every single query like:
```yaml
schema_mapping:
    - output: lib/gen/query_login.dart
      schema: lib/gen/schema.graphql
      queries_glob: lib/gen/query_login.graphql
    - output: lib/gen/query_users.dart
      schema: lib/gen/schema.graphql
      queries_glob: lib/gen/query_users.graphql
    - output: lib/gen/query_user.dart
      schema: lib/gen/schema.graphql
      queries_glob: lib/gen/query_user.graphql
```

But that seems excessive.  Especially for projects like mine that have over 30 different query endpoints.

Is there something that I am missing?  Or am I configuring my project incorrectly?  Any help is appreciated.

**Specs**
Artemis version: [e.g. 6.0.3-beta.1]
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/gen/queries.dart
              schema: lib/gen/schema.graphql
              queries_glob: lib/gen/queries.graphql
```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
[INFO] Generating build script...
[INFO] Generating build script completed, took 374ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 73ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 771ms

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 14ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 52ms

[SEVERE] artemis:artemis on lib/$lib$ (cached):

Exception: Two classes were generated with the same name `Users$Query`!
You may want to:
- Make queries_glob stricter, to gather less .graphql files on a single output
- Use alias on one of the places a field of type `Users$Query` is requested
- File a bug on artemis ...
package:artemis/generator.dart 49:5                                     generateLibrary.<fn>
package:artemis/generator/helpers.dart 20:43                            _mergeDuplicatesBy.<fn>.<fn>
dart:collection                                                         MapMixin.update
package:artemis/generator/helpers.dart 20:12                            _mergeDuplicatesBy.<fn>
dart:core                                                               Iterable.forEach
package:artemis/generator/helpers.dart 18:8                             _mergeDuplicatesBy
package:artemis/generator/helpers.dart 32:7                             ExtensionsOnIterable.mergeDuplicatesBy
package:artemis/generator.dart 46:19                                    generateLibrary
package:artemis/builder.dart 129:29                                     GraphQLQueryBuilder.build
package:build                                                           runBuilder
package:build_runner_core/src/generate/build_impl.dart 486:19           _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 302:15  _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 484:23           _SingleBuild._runForInput.<fn>.<fn>
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 441:22           _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                           Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 437:17           _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 375:38           _SingleBuild._runBuilder.<fn>
dart:async                                                              Future.wait
package:build_runner_core/src/generate/build_impl.dart 374:36           _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 320:20           _SingleBuild._runPhases.<fn>.<fn>
package:build_runner_core/src/generate/build_impl.dart                  _SingleBuild._runPhases.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 184:15  _NoOpBuildPerformanceTracker.trackBuildPhase
package:build_runner_core/src/generate/build_impl.dart 316:47           _SingleBuild._runPhases.<fn>
package:timing/src/timing.dart 222:44                                   NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 310:32           _SingleBuild._runPhases
package:build_runner_core/src/logging/logging.dart 25:30                logTimedAsync
package:build_runner_core/src/generate/build_impl.dart 267:26           _SingleBuild._safeBuild.<fn>
dart:async                                                              runZoned
package:build_runner_core/src/generate/build_impl.dart 262:5            _SingleBuild._safeBuild
package:build_runner_core/src/generate/build_impl.dart 209:24           _SingleBuild.run
package:build_runner_core/src/generate/build_impl.dart 94:56            BuildImpl.run
package:build_runner_core/src/generate/build_runner.dart 25:14          BuildRunner.run
package:build_runner                                                    BuildCommand.run
package:args/command_runner.dart 197:27                                 CommandRunner.runCommand
package:args/command_runner.dart 112:25                                 CommandRunner.run.<fn>
dart:async                                                              new Future.sync
package:args/command_runner.dart 112:14                                 CommandRunner.run
package:build_runner                                                    run
.dart_tool/build/entrypoint/build.dart 31:22                            main

[SEVERE] Build:
Failed after 114ms
pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:338:7)
<asynchronous suspension>
#2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:239:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#7      _rootRun (dart:async/zone.dart:1184:13)
#8      _CustomZone.run (dart:async/zone.dart:1077:19)
#9      _runZoned (dart:async/zone.dart:1619:10)
#10     runZoned (dart:async/zone.dart:1539:10)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#17     _rootRun (dart:async/zone.dart:1184:13)
#18     _CustomZone.run (dart:async/zone.dart:1077:19)
#19     _runZoned (dart:async/zone.dart:1619:10)
#20     runZoned (dart:async/zone.dart:1539:10)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#24     new Future.sync (dart:async/future.dart:224:31)
#25     CommandRunner.run (package:args/command_runner.dart:112:14)
#26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#27     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _runZoned (dart:async/zone.dart:1619:10)
#31     runZonedGuarded (dart:async/zone.dart:1608:12)
#32     runZoned (dart:async/zone.dart:1536:12)
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#34     run.<anonymous closure> (package:flutter_tools/runner.dart)
#35     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#36     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#37     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#38     _rootRun (dart:async/zone.dart:1184:13)
#39     _CustomZone.run (dart:async/zone.dart:1077:19)
#40     _runZoned (dart:async/zone.dart:1619:10)
#41     runZoned (dart:async/zone.dart:1539:10)
#42     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#43     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#44     run (package:flutter_tools/runner.dart:48:10)
#45     main (package:flutter_tools/executable.dart:69:9)
#46     main (file:///Users/mwingfield/Applications/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)




```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
type Query {
    login(email:String!, password:String!): String!
    users(email: String): [String!]!
    user(id:ID!): String!
}
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql

#query Login {
#    login(email: "", password: "")
#}

query Users {
    users(email: "")
}

query User {
    user(id: "")
}
```
</details>

**Comment by vasilich6107** [comment]
The duplication issue was addressed later in the beta branch. Please update to the latest beta version.

**Comment by vasilich6107** [comment]
https://github.com/comigor/artemis/blob/beta/CHANGELOG.md#6010-beta1
