### ISSUE TITLE
Couldn't generate 'fromJson' code for 'file'

### ISSUE THREAD

**Issue by Khosbayar** [comigor/artemis#333]
**Before reporting a bug, please test the beta branch!**

## Bug description
I'm using `MultipartFile` for Upload type (in GraphQL). 
But when I run buid_runner, I'm getting error on FIle conversion (Upload scalar on GraphQL and MultipartFile on Dart).
I have added custom parser in `build.yaml` file - `graphql_serializer.dart` below. I'm not sure what is wrong. 
Please could someone help me on this?

## Specs
Artemis version: ^7.0.0-beta.10
<details>
<summary>graphql_serializer.dart:</summary>
  
```dart
export 'package:http/http.dart';

MultipartFile fromGraphQLUploadToDartMultipartFile(MultipartFile file) => file;
MultipartFile fromDartMultipartFileToGraphQLUpload(MultipartFile file) => file;
List<MultipartFile> fromGraphQLListUploadToDartListMultipartFile(
    List<MultipartFile> files) =>
    files;
List<MultipartFile> fromDartListMultipartFileToGraphQLListUpload(
    List<MultipartFile> files) =>
    files;
```
</details>
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql/*.graphql
              output: lib/graphql/api.dart
          scalar_mapping:
            - graphql_type: Upload
              custom_parser_import: lib/graphql/serializer/graphql_serializer.dart
              dart_type:
                name: MultipartFile
                imports:
                  - 'package:http/http.dart'
              use_custom_parser: true
```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
[  +86 ms] executing: sysctl hw.optional.arm64
[  +15 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +7 ms] executing: [/Users/josh.buyandalai/android-projects/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +14 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b22742018b3edf16c6cadd7b76d9db5e7f9064b5
[        ] executing: [/Users/josh.buyandalai/android-projects/flutter/] git tag --points-at b22742018b3edf16c6cadd7b76d9db5e7f9064b5
[  +25 ms] Exit code 0 from: git tag --points-at b22742018b3edf16c6cadd7b76d9db5e7f9064b5
[        ] 2.2.0
[   +7 ms] executing: [/Users/josh.buyandalai/android-projects/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/josh.buyandalai/android-projects/flutter/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +115 ms] executing: [/Users/josh.buyandalai/android-projects/flutter/] git rev-parse --abbrev-ref HEAD
[  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +8 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +17 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.1
[        ] executing: sw_vers -buildVersion
[  +16 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20C69
[  +78 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +63 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +42 ms] Using /Users/josh.buyandalai/android-projects/flutter/.pub-cache for the pub cache.
[        ] executing: /Users/josh.buyandalai/android-projects/flutter/bin/cache/dart-sdk/bin/pub run build_runner build --verbose
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 402ms

[WARNING] build.fallback:
The package `uploader` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$
[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 65ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 442ms

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 14ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 42ms

[SEVERE] json_serializable:json_serializable on lib/graphql/api.graphql.dart (cached):

Could not generate `fromJson` code for `file`.
To support the type `MultipartFile` you can:
* Use `JsonConverter`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonConverter-class.html
* Use `JsonKey` fields `fromJson` and `toJson`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/fromJson.html
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/toJson.html
package:uploader/graphql/api.graphql.dart:53:18
   ╷
53 │   MultipartFile? file;
   │                  ^^^^
   ╵
package:json_serializable/src/decode_helper.dart 201:7     DecodeHelper._deserializeForField
package:json_serializable/src/decode_helper.dart 53:9      DecodeHelper.createFactory.deserializeFun
package:json_serializable/src/decode_helper.dart 303:32    _writeConstructorInvocation.<fn>
dart:core                                                  StringBuffer.writeAll
package:json_serializable/src/decode_helper.dart 301:9     _writeConstructorInvocation
package:json_serializable/src/decode_helper.dart 56:18     DecodeHelper.createFactory
package:json_serializable/src/generator_helper.dart 85:28  GeneratorHelper.generate

[SEVERE] Build:
Failed after 89ms
[+3041 ms] "flutter run" took 3,184ms.
[   +6 ms] pub finished with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:366:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:241:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +196 ms] ensureAnalyticsSent: 180ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
type Mutation {
    uploadFile(upFileInput: FileCreateInput!): UploadResponse
}

input FileCreateInput {
    file: Upload
}

scalar Upload
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
mutation upload($fileCreateInput: FileCreateInput!) {
    uploadFile(upFileInput: $fileCreateInput) {
        returnMessage
        statusCode
    }
}
```
</details>

**Comment by vasilich6107** [comment]
You have nullable ` MultipartFile?` and your converters are for non nullable

https://tppr.me/Kb09J
https://tppr.me/BB8bc

**Comment by Khosbayar** [comment]
Oh, I see, how can I set up as non-nullable MultipartFile when generating?

**Comment by vasilich6107** [comment]
Adjust your serializers to accept and return nullable values

**Comment by Khosbayar** [comment]
Hi @vasilich6107 , thanks for the advice, 
I have tried to make it nullable in the serializer, even tho it still gives below error:
```
[SEVERE] json_serializable:json_serializable on lib/graphql/api.graphql.dart:

Could not generate `fromJson` code for `file`.
To support the type `MultipartFile` you can:
* Use `JsonConverter`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonConverter-class.html
* Use `JsonKey` fields `fromJson` and `toJson`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/fromJson.html
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/toJson.html
package:leialink_v1/graphql/api.graphql.dart:53:18
   ╷
53 │   MultipartFile? file;
   │                  ^^^^
   ╵

```

My serializer now: 
```
export 'package:http/http.dart';

MultipartFile? fromGraphQLUploadToDartMultipartFile(MultipartFile? file) => file;
MultipartFile? fromDartMultipartFileToGraphQLUpload(MultipartFile? file) => file;
```

**Comment by vasilich6107** [comment]
@Khosbayar 
use `fromGraphQLUploadToDartMultipartFileNullable` for nullable converter
use absolute import `package:graphql_toolchain/artemis.dart` instead of relative one

**Comment by vasilich6107** [comment]
released new `7.1.0-beta.0`
with updated converters generation

`file: Upload` 
- `fromGraphQLUploadNullableToDartMultipartFileNullable`
- `fromDartMultipartFileNullableToGraphQLUploadNullable`

`file: Upload!`
- `fromGraphQLUploadToDartMultipartFile`
- `fromDartMultipartFileToGraphQLUpload`

`file: [Upload]`
- `fromGraphQLListNullableUploadNullableToDartListNullableMultipartFileNullable`
- `fromDartListNullableMultipartFileNullableToGraphQLListNullableUploadNullable`

`file: [Upload]!`
- `fromGraphQLListUploadNullableToDartListMultipartFileNullable`
- `fromDartListMultipartFileNullableToGraphQLListUploadNullable`

`file: [Upload!]!`
- `fromGraphQLListUploadToDartListMultipartFile`
- `fromDartListMultipartFileToGraphQLListUpload`

**Comment by Khosbayar** [comment]
Hi @vasilich6107 ,
Sorry I didn't understand how to do the below step:
_**use absolute import package:graphql_toolchain/artemis.dart instead of relative one**_

**Comment by Khosbayar** [comment]
I have updated artemis version and my serializer is now:
```
export 'package:http/http.dart';

MultipartFile? fromGraphQLUploadNullableToDartMultipartFileNullable(
        MultipartFile? file) =>
    file;

MultipartFile? fromDartMultipartFileNullableToGraphQLUploadNullable(
        MultipartFile? file) =>
    file;
```
So that now they match (`serializer.dart` and `api.graphql.dart`)

**Comment by Khosbayar** [comment]
But still gives the same error.

**Comment by vasilich6107** [comment]
Go into generated file and fix the import issue this is how you’ll get absolute import

**Comment by vasilich6107** [comment]
You need to refer to your serializers via absolute path in build yaml

**Comment by vasilich6107** [comment]
package:your_app_name/path_to_file_without_lib

**Comment by Khosbayar** [comment]
Ah! that was it, thank you so much for the quick replies.

**Comment by Khosbayar** [comment]
Hey @vasilich6107 ,
After updating environment sdk to ">=2.12.0 <3.0.0", 
it gives below error when running `flutter pub run build_runner build`

 ```
lib/graphql/serializer/graphql_serializer.dart:3:1: Error: Type 'MultipartFile' not found.
    MultipartFile? fromGraphQLUploadNullableToDartMultipartFileNullable(
    ^^^^^^^^^^^^^
    lib/graphql/serializer/graphql_serializer.dart:4:9: Error: Type 'MultipartFile' not found.
            MultipartFile? file) =>
            ^^^^^^^^^^^^^
    lib/graphql/serializer/graphql_serializer.dart:7:1: Error: Type 'MultipartFile' not found.
    MultipartFile? fromDartMultipartFileNullableToGraphQLUploadNullable(
    ^^^^^^^^^^^^^
    lib/graphql/serializer/graphql_serializer.dart:8:9: Error: Type 'MultipartFile' not found.
            MultipartFile? file) =>
            ^^^^^^^^^^^^^
    lib/graphql/serializer/graphql_serializer.dart:4:9: Error: 'MultipartFile' isn't a type.
            MultipartFile? file) =>
            ^^^^^^^^^^^^^
    lib/graphql/serializer/graphql_serializer.dart:8:9: Error: 'MultipartFile' isn't a type.
            MultipartFile? file) =>
            ^^^^^^^^^^^^^
```

Is it related to null-safety?

**Comment by vasilich6107** [comment]
@Khosbayar are you missing an import statement?

**Comment by Khosbayar** [comment]
Which one do you mean? http? If so, I have imported on `build.yaml`

```
- graphql_type: Upload
              custom_parser_import: 'package:app/graphql/serializer/graphql_serializer.dart'
              dart_type:
                name: MultipartFile
                imports:
                  - 'package:http/http.dart'
              use_custom_parser: true
```

**Comment by vasilich6107** [comment]
It seems that you are missing import inside your custom parser file

**Comment by Khosbayar** [comment]
Oh do I have to import in my serializer like below?

```
export 'package:http/http.dart';
import 'package:http/http.dart';

MultipartFile? fromGraphQLUploadNullableToDartMultipartFileNullable(
        MultipartFile? file) =>
    file;

MultipartFile? fromDartMultipartFileNullableToGraphQLUploadNullable(
        MultipartFile? file) =>
    file;

```

It works in this case

**Comment by vasilich6107** [comment]
Yes
You need only import, no export required

**Comment by vasilich6107** [comment]
@Khosbayar if `it works` i'm closing the issue

**Comment by vasilich6107** [comment]
Added samples for some possible Upload types
https://github.com/artflutter/graphql_toolchain

**Comment by Khosbayar** [comment]
Thanks @vasilich6107
