### ISSUE TITLE
'TargetKind' incompatibility with current meta / analyzer packages

### ISSUE THREAD

**Issue by LasseRosenow** [comigor/artemis#347]
## Bug description
When I generate my schema with the current flutter version and all current packages I get this error:
```bash
Failed to build build_runner:build_runner:
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-1.7.0/lib/src/error/best_practices_verifier.dart:266:50: Error: The property 'displayString' is defined in multiple extensions for 'TargetKind' and neither is more specific.
 - 'TargetKind' is from 'package:meta/meta_meta.dart' ('../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart').
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
        var kindNames = kinds.map((kind) => kind.displayString).toList()
                                                 ^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-1.7.0/lib/src/error/best_practices_verifier.dart:2000:14: Context: This is one of the extension members.
  String get displayString {
             ^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart:91:14: Context: This is one of the extension members.
  String get displayString {
             ^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-1.7.0/lib/src/error/best_practices_verifier.dart:268:36: Error: The getter 'commaSeparatedWithOr' isn't defined for the class 'List<dynamic>'.
 - 'List' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'commaSeparatedWithOr'.
        var validKinds = kindNames.commaSeparatedWithOr;
                                   ^^^^^^^^^^^^^^^^^^^^
pub finished with exit code 1

```

## Specs
Artemis version: 7.1.1-beta.1
<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - schema.graphql
      - lib/**
      - graphql/**
      - $package$
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql/orders.query.graphql
              output: lib/gen/graphql/orders.query.graphql.dart
              naming_scheme: simple
          custom_parser_import: 'package:lumic/graphql_parser.dart'
          scalar_mapping:
            - graphql_type: DateTime
              dart_type: DateTime
              use_custom_parser: true
```
</details>
<details>
<summary>Artemis output:</summary>
  
```bash
PS C:\Users\Lasse\Desktop\cedgetec\erp\fluttter-app> flutter pub run build_runner build --verbose
[  +96 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +655 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] cc00e7e6bc281f6af9a257e7e33868ef782b1cf7
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at cc00e7e6bc281f6af9a257e7e33868ef782b1cf7
[ +107 ms] Exit code 0 from: git tag --points-at cc00e7e6bc281f6af9a257e7e33868ef782b1cf7
[        ] 2.4.0-4.0.pre
[  +13 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +69 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +65 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +167 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +74 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +91 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +70 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +41 ms] executing: C:\src\flutter\bin\cache\dart-sdk\bin\pub run build_runner build --verbose
Failed to build build_runner:build_runner:
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-1.7.0/lib/src/error/best_practices_verifier.dart:266:50: Error: The property 'displayString' is defined in multiple extensions for 'TargetKind' and neither is more specific.
 - 'TargetKind' is from 'package:meta/meta_meta.dart' ('../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart').
Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
        var kindNames = kinds.map((kind) => kind.displayString).toList()
                                                 ^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-1.7.0/lib/src/error/best_practices_verifier.dart:2000:14: Context: This is one of the extension members.
  String get displayString {
             ^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart:91:14: Context: This is one of the extension members.
  String get displayString {
             ^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-1.7.0/lib/src/error/best_practices_verifier.dart:268:36: Error: The getter 'commaSeparatedWithOr' isn't defined for the class 'List<dynamic>'.
 - 'List' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'commaSeparatedWithOr'.
        var validKinds = kindNames.commaSeparatedWithOr;
                                   ^^^^^^^^^^^^^^^^^^^^
[+3066 ms] "flutter run" took 3.223ms.
[   +7 ms] pub finished with exit code 1
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:365:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:246:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +112 ms] ensureAnalyticsSent: 109ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
</details>

**Comment by vasilich6107** [comment]
@LasseRosenow you did not filled bug report properly.
Where is the schema and query. How should we reproduce the issue?

**Comment by vasilich6107** [comment]
@LasseRosenow closing this issue due to the lack of feedback
Feel free to reopen

**Comment by LasseRosenow** [comment]
I actually fixed it by overriding the analyzer dependency to the newer 2.0.0 release. So this issue will be automatically resolved by updating the dependencies. Which is blocked by gql_code_builder not supporting the newer analyzer yet.

**Comment by vasilich6107** [comment]
Thanks for clarification
