### ISSUE TITLE
Single quote in double-quoted string gives error

### ISSUE THREAD

**Issue by martinolsson** [comigor/artemis#373]
**Before reporting a bug, please test the beta branch!**

## Bug description

When building from a schema with a single quote in a double quoted string, like this:

```qraphql
type Thing {
  id: Int!
  exists: Boolean @deprecated(reason: "A thing's existence cannot be proven")
}
```

I get errors like this:

```

Could not format because the source could not be parsed:

line 11, column 2 of .: Expected to find ')'.
   ╷
11 │  }
   │  ^
   ╵
```

If I remove the single quote it works as expected.

I expect the double-quoted string to allow a single quote character.

## Specs
Artemis version: 7.3.2-beta

<details>
<summary>build.yaml:</summary>
  
```yaml
targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
    builders:
      artemis:
        options:
          scalar_mapping:
            - graphql_type: Int32
              dart_type: int
          schema_mapping:
            - output: lib/graphql_api.dart
              schema: schema.graphql
              queries_glob: graphql/*.graphql
              naming_scheme: pathedWithFields
```
</details>
<details>
<summary>Artemis output:</summary>

```
❯ flutter pub run build_runner build --delete-conflicting-outputs --verbose
[ +127 ms] executing: sysctl hw.optional.arm64
[  +22 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +8 ms] executing: [/usr/local/Caskroom/flutter/2.10.2/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +20 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 7e9793dee1b85a243edd0e06cb1658e98b077561
[        ] executing: [/usr/local/Caskroom/flutter/2.10.2/flutter/] git tag --points-at 7e9793dee1b85a243edd0e06cb1658e98b077561
[ +112 ms] Exit code 0 from: git tag --points-at 7e9793dee1b85a243edd0e06cb1658e98b077561
[        ] 2.10.3
[  +10 ms] executing: [/usr/local/Caskroom/flutter/2.10.2/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/usr/local/Caskroom/flutter/2.10.2/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +126 ms] executing: [/usr/local/Caskroom/flutter/2.10.2/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +7 ms] executing: sw_vers -productName
[  +23 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +18 ms] Exit code 0 from: sw_vers -productVersion
[        ] 12.2.1
[        ] executing: sw_vers -buildVersion
[  +19 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 21D62
[  +81 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +56 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +138 ms] Using /usr/local/Caskroom/flutter/2.10.2/flutter/.pub-cache for the pub cache.
[        ] executing: /usr/local/Caskroom/flutter/2.10.2/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub run build_runner build --delete-conflicting-outputs --verbose
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 550ms

[WARNING] build.fallback:
The package `artemis_quotes_bug` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$
[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 69ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 792ms

[INFO] Build:Running build...
[FINE] artemis:artemis on lib/$lib$:-> Class
[FINE] artemis:artemis on lib/$lib$:┌ [TypeName(name:r'Thing'), TypeName(name:r'RootQuery')][RootQuery][null null] ()
[FINE] artemis:artemis on lib/$lib$:|   [TypeName(name:r'Thing'), TypeName(name:r'RootQuery')][RootQuery][ClassName(name:r'Thing') ClassPropertyName(name:r'thing')] -> Thing$RootQuery$Thing
[FINE] artemis:artemis on lib/$lib$:|   -> Class
[FINE] artemis:artemis on lib/$lib$:|   ┌ [TypeName(name:r'Thing'), TypeName(name:r'RootQuery'), ClassPropertyName(name:r'thing')][Thing][null null] ()
[FINE] artemis:artemis on lib/$lib$:|   |   [TypeName(name:r'Thing'), TypeName(name:r'RootQuery'), ClassPropertyName(name:r'thing')][Thing][ClassName(name:r'Int') ClassPropertyName(name:r'id')] -> int
[FINE] artemis:artemis on lib/$lib$:|   |   [TypeName(name:r'Thing'), TypeName(name:r'RootQuery'), ClassPropertyName(name:r'thing')][Thing][ClassName(name:r'Boolean') ClassPropertyName(name:r'exists')] -> bool?
[FINE] artemis:artemis on lib/$lib$:|   └ [TypeName(name:r'Thing'), TypeName(name:r'RootQuery'), ClassPropertyName(name:r'thing')][Thing][null null] ()
[FINE] artemis:artemis on lib/$lib$:|   <- Generated class Thing$RootQuery$Thing.
[FINE] artemis:artemis on lib/$lib$:└ [TypeName(name:r'Thing'), TypeName(name:r'RootQuery')][RootQuery][null null] ()
[FINE] artemis:artemis on lib/$lib$:<- Generated class Thing$RootQuery.
[WARNING] artemis:artemis on lib/$lib$:
Closure: (VariableDefinitionNode) => void from Function 'visitVariableDefinitionNode':.
[SEVERE] artemis:artemis on lib/$lib$:

Could not format because the source could not be parsed:

line 11, column 2 of .: Expected to find ')'.
   ╷
11 │  }
   │  ^
   ╵
line 7, column 44 of .: Expected to find ','.
  ╷
7 │ @Deprecated('A thing's existance cannot be proven')  bool? exists;
  │                                            ^^^^^^
  ╵
line 7, column 66 of .: Unterminated string literal.
  ╷
7 │ @Deprecated('A thing's existance cannot be proven')  bool? exists;
  │                                                                  ^
  ╵
line 7, column 50 of .: Expected to find ','.
  ╷
7 │ @Deprecated('A thing's existance cannot be proven')  bool? exists;
  │                                                  ^^^^^^^^^^^^^^^^^
  ╵
line 7, column 34 of .: Expected to find ','.
  ╷
7 │ @Deprecated('A thing's existance cannot be proven')  bool? exists;
  │                                  ^^^^^^
  ╵
line 7, column 22 of .: Expected to find ','.
  ╷
7 │ @Deprecated('A thing's existance cannot be proven')  bool? exists;
  │                      ^
  ╵
line 7, column 24 of .: Expected to find ','.
  ╷
7 │ @Deprecated('A thing's existance cannot be proven')  bool? exists;
  │                        ^^^^^^^^^
  ╵
line 7, column 41 of .: Expected to find ','.
  ╷
7 │ @Deprecated('A thing's existance cannot be proven')  bool? exists;
  │                                         ^^
  ╵
package:dart_style/src/dart_formatter.dart 144:7     DartFormatter.formatSource
package:dart_style/src/dart_formatter.dart 72:12     DartFormatter.format
package:artemis/generator/print_helpers.dart 423:26  specToString
package:artemis/generator/print_helpers.dart 441:16  writeLibraryDefinitionToBuffer
package:artemis/builder.dart 200:7                   GraphQLQueryBuilder.build

[INFO] Build:Running build completed, took 390ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 37ms

[SEVERE] Build:
Failed after 441ms
[+4016 ms] "flutter run" took 4,259ms.
[   +6 ms] pub finished with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:416:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:251:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[  +51 ms] ensureAnalyticsSent: 49ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

~/artemis_quotes_bug master*
❯ 
```
</details>
<details>
<summary>GraphQL schema:</summary>

```graphql
schema {
  query: RootQuery
}

type RootQuery {
  thing(id: Int!): Thing!
}

type Thing {
  id: Int!
  exists: Boolean @deprecated(reason: "A thing's existence cannot be proven")
}
```
</details>
<details>
<summary>GraphQL query:</summary>

```graphql
query Thing($id: ID!) {
  thing(id: $id) {
    id
    exists
  }
}
```
</details>

**Comment by vasilich6107** [comment]
@martinolsson fixed in [7.3.3-beta](https://pub.dev/packages/artemis/versions/7.3.3-beta)
